---
- name: System Status Checker
  hosts: clients
  gather_facts: yes

  tasks:
    - name: Gather CPU usage
      shell: top -bn1 | grep 'Cpu(s)' | awk '{print $2}'
      register: cpu_usage

    - name: Gather RAM usage RHEL
      shell: free --mega | awk '/Mem/ {print $3/$2 * 100}'
      register: ram_usage

    - name: Gather Disk space
      shell: "df -h --output=pcent / | awk 'NR==2 {print $1}'"
      register: disk_space

    - name: Usage Stats
      debug:
        msg:
          - "Executed On: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
          - "CPU Usage: {{ cpu_usage.stdout }}%"
          - "RAM Usage: {{ ram_usage.stdout }}%"
          - "Disk Space Used: {{ disk_space.stdout }}"
